# Generated by Django 6.0.5 on 2026-05-22 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_user_credits_remaining_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('job_seeker', '🔍 Job Seeker (Actively looking for jobs)'), ('fresher', '🎓 Fresher / Recent Graduate'), ('student', '📚 Student (UG/PG)'), ('experienced', '💼 Experienced Professional (3+ years)'), ('career_changer', '🔄 Career Changer'), ('internship', '📝 Looking for Internship'), ('recruiter', '👔 Recruiter / HR Professional'), ('freelancer', '💻 Freelancer'), ('entrepreneur', '🚀 Entrepreneur / Business Owner'), ('returning', '🔄 Returning to Workforce')], default='job_seeker', max_length=50),
        ),
        migrations.AlterModelTable(
            name='user',
            table='accounts_user',
        ),
    ]
