# Generated by Django 6.0.5 on 2026-05-21 12:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resume_file', models.FileField(upload_to='resumes/%Y/%m/%d/')),
                ('job_description', models.TextField()),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('resume_text', models.TextField(blank=True)),
                ('ats_score', models.IntegerField(default=0)),
                ('critical_skills_match', models.FloatField(default=0)),
                ('skills_match', models.FloatField(default=0)),
                ('profile_match', models.FloatField(default=0)),
                ('format_score', models.FloatField(default=0)),
                ('missing_keywords', models.JSONField(default=list)),
                ('found_keywords', models.JSONField(default=list)),
                ('critical_skills', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeatmapData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_zones', models.JSONField(default=dict)),
                ('keyword_positions', models.JSONField(default=dict)),
                ('heatmap_image', models.ImageField(blank=True, null=True, upload_to='heatmaps/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heatmap', to='analyzer.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='RewriteSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('suggested_text', models.TextField()),
                ('context_section', models.CharField(max_length=100)),
                ('keyword_added', models.CharField(blank=True, max_length=255)),
                ('accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewrites', to='analyzer.analysis')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField()),
                ('content', models.TextField()),
                ('file', models.FileField(upload_to='versions/%Y/%m/%d/')),
                ('ats_score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analysis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='analyzer.analysis')),
                ('parent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analyzer.resumeversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('user', 'version_number')},
            },
        ),
    ]
